// Renders the pass artwork once, from the brand files, into a TypeScript
// module of base64 strings - so the serverless function carries its images
// with it instead of hoping the files are traced into the bundle.
import { readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const INK = "#02251f";
const NEON = "#cef870";
const logoSvg = readFileSync("public/logo-dark.svg");

// Wide logo: 160x50 points, the logo's own aspect (1412x381) decides the height.
async function logo(scale) {
  const w = 160 * scale;
  const h = Math.round((381 / 1412) * w);
  return sharp(logoSvg).resize(w, h).png().toBuffer();
}

// Square icon: the summit's initials on ink, the way the site's favicon reads.
async function icon(scale) {
  const s = 29 * scale;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 29 29">
    <rect width="29" height="29" rx="6" fill="${INK}"/>
    <text x="14.5" y="19.6" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-weight="800" font-size="13" fill="${NEON}" letter-spacing="-0.5">SLS</text>
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

// The strip carries the event's name as typography, in the site's display
// face, at a size chosen by eye - Wallet's own primary field can only draw
// it huge. Rendered in a headless browser because that is the one renderer
// here that lays out a web font the way the site does; drawn once at 3x
// and scaled down for the smaller densities.
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";

async function renderStrip3x() {
  const dir = mkdtempSync(join(tmpdir(), "strip-"));
  const font = resolve("scripts/wallet/fonts/Unbounded-800.woff2");
  // Ink at every edge, so the strip meets the pass's flat colour without a
  // seam; a soft glow of pine with a breath of teal in the middle, and a
  // fine grain over it all so the gradient reads as material, not as a fill.
  const html = `<!doctype html><meta charset="utf-8"><style>
    @font-face{font-family:U;src:url("file://${font}") format("woff2");font-weight:800}
    html,body{margin:0;background:${INK}}
    .s{position:relative;width:375px;height:98px;overflow:hidden;background:
      radial-gradient(95% 62% at 74% 52%, rgba(20,100,85,.95) 0%, rgba(20,100,85,.55) 32%, rgba(2,37,31,0) 72%),
      radial-gradient(50% 45% at 92% 18%, rgba(14,205,183,.22) 0%, rgba(2,37,31,0) 70%),
      radial-gradient(40% 40% at 6% 88%, rgba(206,248,112,.10) 0%, rgba(2,37,31,0) 70%),
      ${INK}}
    .g{position:absolute;inset:0;opacity:.09;mix-blend-mode:soft-light;
      background-image:url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/><feColorMatrix values='0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0 0 0 1 0'/></filter><rect width='200' height='200' filter='url(%23n)'/></svg>")}
    .t{position:absolute;left:16px;top:50%;transform:translateY(-50%);font:800 21px/1 U,sans-serif;letter-spacing:-.02em;color:#e9f0ec;text-transform:uppercase}
    .t small{display:block;margin-top:7px;font:500 8.5px/1 -apple-system,Helvetica,Arial,sans-serif;letter-spacing:.22em;color:${NEON}}
  </style><body><div class="s"><div class="g"></div>
  <div class="t">Sofia Life Summit<small>LONGEVITY · SOFIA 2026</small></div></div>`;
  const page = join(dir, "strip.html");
  writeFileSync(page, html);
  const out = join(dir, "strip.png");
  execFileSync(CHROME, [
    "--headless=new", "--disable-gpu", "--hide-scrollbars", "--allow-file-access-from-files",
    "--force-device-scale-factor=3", "--window-size=375,98", `--screenshot=${out}`, `file://${page}`,
  ], { stdio: "ignore" });
  const buf = readFileSync(out);
  rmSync(dir, { recursive: true, force: true });
  return buf;
}

let strip3x;
async function strip(scale) {
  strip3x ??= await renderStrip3x();
  if (scale === 3) return strip3x;
  return sharp(strip3x).resize(375 * scale, 98 * scale).png().toBuffer();
}

const out = {};
for (const [name, fn] of [["icon", icon], ["logo", logo], ["strip", strip]]) {
  for (const scale of [1, 2, 3]) {
    const key = scale === 1 ? `${name}.png` : `${name}@${scale}x.png`;
    out[key] = (await fn(scale)).toString("base64");
  }
}
const ts = `// Generated by scripts/wallet/render-images.mjs - do not edit by hand.
/** The pass artwork, base64, keyed by the file name Wallet expects. */
export const WALLET_IMAGES: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/lib/wallet-images.ts", ts);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${Math.round((v.length * 3) / 4 / 1024)} KB`).join("\n"));
