// Renders the pass artwork once, from the brand files, into a TypeScript
// module of base64 strings - so the serverless function carries its images
// with it instead of hoping the files are traced into the bundle.
import { readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const INK = "#02251f";
const NEON = "#cef870";
const logoSvg = readFileSync("public/logo-dark.svg");

// Wide logo: 160x50 points, the logo's own aspect (1412x381) decides the height.
async function logo(scale) {
  const w = 160 * scale;
  const h = Math.round((381 / 1412) * w);
  return sharp(logoSvg).resize(w, h).png().toBuffer();
}

// Square icon: the summit's initials on ink, the way the site's favicon reads.
async function icon(scale) {
  const s = 29 * scale;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 29 29">
    <rect width="29" height="29" rx="6" fill="${INK}"/>
    <text x="14.5" y="19.6" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-weight="800" font-size="13" fill="${NEON}" letter-spacing="-0.5">SLS</text>
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

// Strip behind the primary field: ink with a faint diagonal neon band, no
// text - the words belong to the fields, where they can be in either language.
async function strip(scale) {
  const w = 375 * scale, h = 98 * scale;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 375 98">
    <rect width="375" height="98" fill="${INK}"/>
    <path d="M250 -10 L375 -10 L375 108 L190 108 Z" fill="${NEON}" opacity="0.10"/>
    <path d="M300 -10 L375 -10 L375 108 L240 108 Z" fill="#0ecdb7" opacity="0.10"/>
    <circle cx="352" cy="24" r="5" fill="${NEON}"/>
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

const out = {};
for (const [name, fn] of [["icon", icon], ["logo", logo], ["strip", strip]]) {
  for (const scale of [1, 2, 3]) {
    const key = scale === 1 ? `${name}.png` : `${name}@${scale}x.png`;
    out[key] = (await fn(scale)).toString("base64");
  }
}
const ts = `// Generated by scripts/wallet/render-images.mjs - do not edit by hand.
/** The pass artwork, base64, keyed by the file name Wallet expects. */
export const WALLET_IMAGES: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/lib/wallet-images.ts", ts);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${Math.round((v.length * 3) / 4 / 1024)} KB`).join("\n"));
