// Renders the pass artwork once, from the brand files, into a TypeScript
// module of base64 strings - so the serverless function carries its images
// with it instead of hoping the files are traced into the bundle.
import { readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const INK = "#02251f";
const NEON = "#cef870";
const logoSvg = readFileSync("public/logo-dark.svg");

// The organiser's logo, top left, the way it sits on the site. 160x50
// points is the most Wallet gives it; the logo's own aspect sets the height.
async function logo(scale) {
  const w = 160 * scale;
  const h = Math.round((381 / 1412) * w);
  return sharp(logoSvg).resize(w, h).png().toBuffer();
}

// Square icon: the summit's initials on ink, the way the site's favicon reads.
async function icon(scale) {
  const s = 29 * scale;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 29 29">
    <rect width="29" height="29" rx="6" fill="${INK}"/>
    <text x="14.5" y="19.6" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" font-weight="800" font-size="13" fill="${NEON}" letter-spacing="-0.5">SLS</text>
  </svg>`;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";

// Renders one HTML fragment at 3x in a headless browser - the one renderer
// here that lays out a web font the way the site does.
function renderHtml(w, h, body, css) {
  const dir = mkdtempSync(join(tmpdir(), "pass-"));
  const font = resolve("scripts/wallet/fonts/Unbounded-800.woff2");
  const page = join(dir, "p.html");
  writeFileSync(page, `<!doctype html><meta charset="utf-8"><style>
    @font-face{font-family:U;src:url("file://${font}") format("woff2");font-weight:800;font-display:block}
    html,body{margin:0;background:transparent}
    .frame{position:relative;width:${w}px;height:${h}px;overflow:hidden}
    ${css}</style><body><div class="frame">${body}</div>`);
  const out = join(dir, "p.png");
  execFileSync(CHROME, [
    "--headless=new", "--disable-gpu", "--hide-scrollbars", "--allow-file-access-from-files",
    "--default-background-color=00000000", "--force-device-scale-factor=3",
    // Lets the font arrive before the shot; without it the text is missing.
    "--virtual-time-budget=4000",
    `--window-size=${w},${h}`, `--screenshot=${out}`, `file://${page}`,
  ], { stdio: "ignore" });
  const buf = readFileSync(out);
  rmSync(dir, { recursive: true, force: true });
  return buf;
}

const scaled = (buf3x, w, h) => async (scale) =>
  scale === 3 ? buf3x : sharp(buf3x).resize(w * scale, h * scale).png().toBuffer();

// The whole front: ink with a glow of pine and a breath of teal. Wallet
// blurs and slightly crops it, which is what makes the gradient velvet.
const bgPng = renderHtml(180, 220, `<div class="b"></div>`, `
  .b{width:180px;height:220px;background:
    radial-gradient(90% 60% at 80% 28%, rgba(20,100,85,1) 0%, rgba(20,100,85,.55) 38%, rgba(2,37,31,0) 75%),
    radial-gradient(60% 45% at 100% 8%, rgba(14,205,183,.30) 0%, rgba(2,37,31,0) 70%),
    radial-gradient(70% 50% at 0% 100%, rgba(206,248,112,.14) 0%, rgba(2,37,31,0) 70%),
    ${INK}}`);
const background = scaled(bgPng, 180, 220);

const out = {};
for (const [name, fn] of [["icon", icon], ["logo", logo], ["background", background]]) {
  for (const scale of [1, 2, 3]) {
    const key = scale === 1 ? `${name}.png` : `${name}@${scale}x.png`;
    out[key] = (await fn(scale)).toString("base64");
  }
}
const ts = `// Generated by scripts/wallet/render-images.mjs - do not edit by hand.
/** The pass artwork, base64, keyed by the file name Wallet expects. */
export const WALLET_IMAGES: Record<string, string> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync("src/lib/wallet-images.ts", ts);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${Math.round((v.length * 3) / 4 / 1024)} KB`).join("\n"));
